// packages/devextreme-cli/src/templates/nextjs/application/src/components/change-password-form/ChangePasswordForm.tsx
'use client'
import <%=#isTypeScript%>React, <%=/isTypeScript%>{ useState, useRef, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import Form, {
  Item,
  Label,
  ButtonItem,
  ButtonOptions,
  RequiredRule,
  CustomRule,
} from 'devextreme-react/form';
import LoadIndicator from 'devextreme-react/load-indicator';
import notify from 'devextreme/ui/notify';
<%=#isTypeScript%>import { ValidationCallbackData } from 'devextreme-react/common';<%=/isTypeScript%>
import { changePassword } from '../../api/auth';

export default function ChangePasswordForm() {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const formData = useRef({ password: '' });

  const onSubmit = useCallback(async (e<%=#isTypeScript%>: React.FormEvent<HTMLFormElement><%=/isTypeScript%>) => {
  e.preventDefault();
  const { password } = formData.current;
  setLoading(true);

  const result = await changePassword(password);
  setLoading(false);

  if (result.isOk) {
    router.push('/login');
  } else {
    notify(result.message, 'error', 2000);
  }
}, [router]);

const confirmPassword = useCallback(
  ({ value }<%=#isTypeScript%>: ValidationCallbackData<%=/isTypeScript%>) => value === formData.current.password,
  []
);

return (
  <form onSubmit={onSubmit}>
    <Form formData={formData.current} disabled={loading}>
      <Item
        dataField={'password'}
        editorType={'dxTextBox'}
        editorOptions={passwordEditorOptions}
      >
        <RequiredRule message="Password is required" />
        <Label visible={false} />
      </Item>
      <Item
        dataField={'confirmedPassword'}
        editorType={'dxTextBox'}
        editorOptions={confirmedPasswordEditorOptions}
      >
        <RequiredRule message="Password is required" />
        <CustomRule
          message={'Passwords do not match'}
          validationCallback={confirmPassword}
        />
        <Label visible={false} />
      </Item>
      <ButtonItem>
        <ButtonOptions
          width={'100%'}
          type={'default'}
          useSubmitBehavior={true}
        >
            <span className="dx-button-text">
              {
                loading
                  ? <LoadIndicator width={'24px'} height={'24px'} visible={true} />
                  : 'Continue'
              }
            </span>
        </ButtonOptions>
      </ButtonItem>
    </Form>
  </form>
);
}

const passwordEditorOptions = { stylingMode: 'filled', placeholder: 'Password', mode: 'password' };
const confirmedPasswordEditorOptions = { stylingMode: 'filled', placeholder: 'Confirm Password', mode: 'password' };

// packages/devextreme-cli/src/templates/vue-v3/application/src/views/change-password-form.vue
<template>
  <form @submit.prevent="onSubmit">
    <dx-form :form-data="formData" :disabled="loading">
      <dx-item
        data-field="password"
        editor-type="dxTextBox"
        :editor-options="{ stylingMode: 'filled', placeholder: 'Password', mode: 'password' }"
      >
        <dx-required-rule message="Password is required" />
        <dx-label :visible="false" />
      </dx-item>
      <dx-item
        data-field="confirmedPassword"
        editor-type="dxTextBox"
        :editor-options="{ stylingMode: 'filled', placeholder: 'Confirm Password', mode: 'password' }"
      >
        <dx-required-rule message="Password is required" />
        <dx-custom-rule
          message="Passwords do not match"
          :validation-callback="confirmPassword"
        />
        <dx-label :visible="false" />
      </dx-item>
      <dx-button-item>
        <dx-button-options
          width="100%"
          type="default"
          template="changePassword"
          :use-submit-behavior="true"
        >
        </dx-button-options>
      </dx-button-item>

      <template #changePassword>
        <div>
          <span class="dx-button-text">
              <dx-loadIndicator v-if="loading" width="24px" height="24px" :visible="true" />
              <span v-if="!loading">Continue</span>
          </span>
        </div>
      </template>
    </dx-form>
  </form>
</template>

<script>
import DxForm, {
  DxItem,
  DxLabel,
  DxButtonItem,
  DxButtonOptions,
  DxCustomRule,
  DxRequiredRule
} from 'devextreme-vue/form';
import DxLoadIndicator from 'devextreme-vue/load-indicator';
import notify from 'devextreme/ui/notify';
import { useRouter, useRoute } from 'vue-router';
import { ref, reactive } from "vue";

import auth from "../auth";

export default {
components: {
    DxForm,
    DxItem,
    DxLabel,
    DxButtonItem,
    DxButtonOptions,
    DxRequiredRule,
    DxCustomRule,
    DxLoadIndicator
  },
  setup() {
    const router = useRouter();
    const route = useRoute();

    const recoveryCode = ref("");
    const loading = ref(false);
    const formData = reactive({
      password:""
    });

    recoveryCode.value = route.params.recoveryCode;

    async function onSubmit() {
      const { password } = formData;
      loading.value = true;
  
      const result = await auth.changePassword(password, recoveryCode.value);
      loading.value = false;
  
      if (result.isOk) {
        router.push("/login-form");
      } else {
        notify(result.message, 'error', 2000);
      }
    }

    function confirmPassword (e) {
      return e.value === formData.password;
    }

    return {
      recoveryCode,
      loading,
      formData,
      onSubmit,
      confirmPassword
    }
  }
}
</script>

<style>

</style>
