// templates/react/src/components/login-form/login-form.js
import React from 'react';
import TextBox from 'devextreme-react/text-box';
import ValidationGroup from 'devextreme-react/validation-group';
import Validator, { ValidationRule } from 'devextreme-react/validator';
import Button from 'devextreme-react/button';
import CheckBox from 'devextreme-react/check-box';
import './login-form.scss';
import appInfo from '../../app-info';
import { Link } from 'react-router-dom';

export default class LoginForm extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      login: '',
      password: ''
    };
  }

  render() {
    const { login, password } = this.state;
    return (
      <ValidationGroup>
        <div className={'login-header'}>
          <div className={'title'}>{appInfo.title}</div>
          <div>Sign In to your account</div>
        </div>
        <div className={'dx-field'}>
          <TextBox
            value={login}
            onValueChanged={this.loginChanged}
            placeholder={'Login'}
            width={'100%'}
          >
            <Validator>
              <ValidationRule type={'required'} message={'Login is required'} />
            </Validator>
          </TextBox>
        </div>
        <div className={'dx-field'}>
          <TextBox
            mode={'password'}
            value={password}
            onValueChanged={this.passwordChanged}
            placeholder={'Password'}
            width={'100%'}
          >
            <Validator>
              <ValidationRule
                type={'required'}
                message={'Password is required'}
              />
            </Validator>
          </TextBox>
        </div>
        <div className={'dx-field'}>
          <CheckBox value={false} text={'Remember me'} />
        </div>
        <div className={'dx-field'}>
          <Button
            type={'default'}
            text={'Login'}
            onClick={this.onLoginClick}
            width={'100%'}
          />
        </div>
        <div className={'dx-field'}>
          <Link to={'/recovery'} onClick={e => e.preventDefault()}>Forgot password ?</Link>
        </div>
        <div className={'dx-field'}>
          <Button type={'normal'} text={'Create an account'} width={'100%'} />
        </div>
      </ValidationGroup>
    );
  }

  loginChanged = e => {
    this.setState({ login: e.value });
  };

  passwordChanged = e => {
    this.setState({ password: e.value });
  };

  onLoginClick = args => {
    if (!args.validationGroup.validate().isValid) {
      return;
    }

    const { login, password } = this.state;
    this.props.onLoginClick(login, password);

    args.validationGroup.reset();
  };
}

// templates/vue/application/src/views/login-form.vue
<template>
  <dx-validation-group>
    <div class="login-header">
      <div class="title">{{ title }}</div>
      <div>Sign In to your account</div>
    </div>

    <div class="dx-field">
      <dx-text-box placeholder="Login" width="100%" :value.sync="login">
        <dx-validator>
          <dx-required-rule message="Login is required" />
        </dx-validator>
      </dx-text-box>
    </div>

    <div class="dx-field">
      <dx-text-box
        placeholder="Password"
        width="100%"
        mode="password"
        :value.sync="password"
      >
        <dx-validator>
          <dx-required-rule message="Password is required" />
        </dx-validator>
      </dx-text-box>
    </div>

    <div class="dx-field">
      <dx-check-box :value.sync="rememberUser" text="Remember me" />
    </div>

    <div class="dx-field">
      <dx-button
        type="default"
        text="Login"
        width="100%"
        @click="onLoginClick"
      />
    </div>

    <div class="dx-field">
      <router-link to="/recovery"><a>Forgot password ?</a></router-link>
    </div>

    <div class="dx-field">
      <dx-button type="normal" text="Create an account" width="100%" />
    </div>
  </dx-validation-group>
</template>

<script>
import DxButton from "devextreme-vue/button";
import DxCheckBox from "devextreme-vue/check-box";
import DxTextBox from "devextreme-vue/text-box";
import DxValidationGroup from "devextreme-vue/validation-group";
import DxValidator, { DxRequiredRule } from "devextreme-vue/validator";

import auth from "../auth";

export default {
  data() {
    return {
      title: this.$appInfo.title,
      login: "",
      password: "",
      rememberUser: false
    };
  },
  methods: {
    onLoginClick(e) {
      if (!e.validationGroup.validate().isValid) {
        return;
      }

      auth.logIn();
      this.$router.push("/home");

      e.validationGroup.reset();
    }
  },
  components: {
    DxButton,
    DxCheckBox,
    DxTextBox,
    DxValidator,
    DxRequiredRule,
    DxValidationGroup
  }
};
</script>

<style lang="scss">
@import "../themes/generated/variables.base.scss";

.login-header {
  text-align: center;
  margin-bottom: 40px;

  .title {
    color: $base-accent;
    font-weight: bold;
    font-size: 30px;
    margin: 0;
  }
}
</style>
